name: PLSQL Code Review

on:
  pull_request:
    branches:
      - main # Update with your branch name

jobs:
  code-review:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'

      - name: Get .plsql files
        run: |
          find . -name "*.plsql" > plsql_files.txt

      - name: Run IfsCodeReview.jar
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          java -jar .github/IfsCodeReview.jar $COMMIT_ID workspace/Test.plsql
        working-directory: ${{ github.workspace }}

      - name: Print comments.json
        run: cat comments.json
        working-directory: ${{ github.workspace }}
        
      - name: Get PR number
        id: pr_number
        run: echo "PR_NUMBER=$(echo ${{ github.event.number }})" >> $GITHUB_ENV
      
      - name: PR Comments
          gh issue comment ${{ github.event.number }} --body "$(<comments.json)"
        
      - name: PR Comment
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
            issue_number: ${{ github.event.number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ':warning: PRs adding apps should generally be made against the [source repo `OWASP/OWASP-VWAD`](https://github.com/OWASP/OWASP-VWAD).'
            })
