name: Add Comments to PR

on:
  pull_request:
    branches:
      - main

jobs:
  code-review:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'

      - name: Run IfsCodeReview.jar
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          java -jar .github/IfsCodeReview.jar $COMMIT_ID workspace/Test.plsql
        working-directory: ${{ github.workspace }}

      - name: Print comments.json
        run: cat comments.json
        working-directory: ${{ github.workspace }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read comments from JSON file
        run: |
          COMMENTS=$(cat comments.json)
          echo "Processing comments:"
          echo "$COMMENTS"
          echo "$COMMENTS" | jq -c '.[]' > comments_temp.json
        shell: bash

      - name: Post comments to PR
        run: |
          for COMMENT in $(jq -c '.[]' comments_temp.json); do
            echo "Posting comment:"
            echo "$COMMENT"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
