name: PLSQL Code Review

on:
  pull_request:
    branches:
      - main # Update with your branch name

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'

      - name: Get .plsql files
        run: |
          find . -name "*.plsql" > plsql_files.txt

      - name: Run IfsCodeReview.jar
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          java -jar .github/IfsCodeReview.jar $COMMIT_ID workspace/Test.plsql
        working-directory: ${{ github.workspace }}

      - name: Print comments.json
        run: cat comments.json
        working-directory: ${{ github.workspace }}
        
      - name: Get PR number
        id: pr_number
        run: echo "PR_NUMBER=$(echo ${{ github.event.number }})" >> $GITHUB_ENV

      - name: Read comments from file
        id: read-comments
        run: |
          echo "::set-output name=comments::$(cat comments.json)"

      - name: Add comments to PR
        if: success() # Condition to check if previous steps were successful
        run: |
          COMMENTS="${{ steps.read-comments.outputs.comments }}"
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          ISSUE_NUMBER="${{ github.event.number }}"
          
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$COMMENTS" \
            "https://api.github.com/repos/$OWNER/$REPO/issues/$ISSUE_NUMBER/comments"
