name: Add Comments to PR

on:
  pull_request:
    branches:
      - main

jobs:
  code-review:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'

      - name: Run IfsCodeReview.jar
        run: |
          COMMIT_SHA=${{ github.sha }}
          OWNER_ID=${{ github.repository_owner }}
          REPO_ID=$(echo ${{ github.repository }} | awk -F/ '{print $NF}')
          PR_NO=${{ github.event.number }}
          env GH_TOKEN=${{ secrets.GH_TOKEN }} OWNER_ID=$OWNER_ID REPO_ID=$REPO_ID PR_NO=$PR_NO java -jar .github/IfsCodeReview.jar $COMMIT_SHA workspace/Test.plsql $OWNER_ID $REPO_ID $PR_NO
        working-directory: ${{ github.workspace }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OWNER_ID: ${{ github.repository_owner }}
          REPO_ID: ${{ github.repository }}
          PR_NO: ${{ github.event.number }}
