name: Custom Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - assigned
      - labeled
    paths:
      - '**/*'

jobs:
  check_assignee:
    runs-on: ubuntu-latest
    outputs:
      assignee_matched: '${{ steps.check_assignee.outputs.assignee_matched }}'
      commit_sha: '${{ steps.check_assignee.outputs.commit_sha }}'
    steps:
      - name: Check Assignee and Label
        id: check_assignee
        run: |
          desired_assignee="pardhu23"
          desired_label="Auto Code Review"

          # Check if the assignee matches
          if [ "${{ github.event.pull_request.assignee.login }}" == "$desired_assignee" ]; then
            assignee_matched=true
          else
            assignee_matched=false
          fi

          # Check if the 'Auto Code Review' label is added
          if [ "$(echo "${{ github.event.pull_request.labels.*.name }}" | grep -c "$desired_label")" -gt 0 ]; then
            label_added=true
          else
            label_added=false
          fi

          commit_sha="${{ github.event.after }}"
          if [ "$commit_sha" == "null" ]; then
            commit_sha="${{ github.event.before }}"
          fi

          # Set outputs
          echo "::set-output name=assignee_matched::$assignee_matched"
          echo "::set-output name=label_added::$label_added"
          echo "::set-output name=commit_sha::$commit_sha"

          # Print values to the console
          echo "Assignee Matched: $assignee_matched"
          echo "Label Added: $label_added"
          echo "Commit SHA: $commit_sha"

  code_review:
    needs: check_assignee
    runs-on: ubuntu-latest
    if: ${{ needs.check_assignee.outputs.assignee_matched == 'true' || (needs.check_assignee.outputs.label_added == 'true' && needs.check_assignee.outputs.commit_sha != 'null') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: adopt
      - name: Set Commit SHA
        run: echo "COMMIT_SHA=${{ needs.check_assignee.outputs.commit_sha }}" >> $GITHUB_ENV
      - name: Run IfsCodeReview.jar
        run: |
          added_files=$(git diff --name-only ${{ needs.check_assignee.outputs.commit_sha }}^ ${{ needs.check_assignee.outputs.commit_sha }})

          for file in $added_files; do
            extension="${file##*.}"
            if [ "$extension" == "plsql" ]; then
              echo "Processing $file"
              COMMIT_SHA="${{ github.event.after }}"
              OWNER_ID="${{ github.repository_owner }}"
              REPO_ID=$(echo ${{ github.repository }} | awk -F/ '{print $NF}')
              PR_NO="${{ github.event.number }}"
              env GH_TOKEN="${{ secrets.GH_TOKEN }}" OWNER_ID="$OWNER_ID" REPO_ID="$REPO_ID" PR_NO="$PR_NO" java -jar .github/IfsCodeReview.jar "$COMMIT_SHA" "$file" "$OWNER_ID" "$REPO_ID" "$PR_NO"
            fi
          done
        working-directory: '${{ github.workspace }}'
        env:
          GH_TOKEN: '${{ secrets.GH_TOKEN }}'
          OWNER_ID: '${{ github.repository_owner }}'
          REPO_ID: '${{ github.repository }}'
          PR_NO: '${{ github.event.number }}'
          COMMIT_SHA: '${{ github.event.after }}'
