name: Add Comments to PR

on:
  pull_request:
    branches:
      - main

jobs:
  code-review:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'

      - name: Run IfsCodeReview.jar
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          java -jar .github/IfsCodeReview.jar $COMMIT_ID workspace/Test.plsql
        working-directory: ${{ github.workspace }}

      - name: Print comments.json
        run: cat comments.json
        working-directory: ${{ github.workspace }}

      - name: Read comments from JSON file
        id: read-comments
        run: |
          COMMENTS=$(cat comments.json)
          echo "$COMMENTS" > /tmp/comments.json
          echo "::set-output name=comments::/tmp/comments.json"

      - name: Post comments to PR
        run: |
          COMMENTS=$(cat ${{ steps.read-comments.outputs.comments }} | jq -c '.[]')
          for COMMENT in $COMMENTS; do
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d "$COMMENT" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/comments"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
