name: Process JSON Items

on:
  push:
    branches:
      - main

jobs:
  process-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Process JSON Items
        run: |
          json='[
            {"body": "SELECT * is not allowed, specify the required columns.","path": "workspace/Test.plsql","line": 11,"commit_id": "90de3a02bdf57cb64bdb7f934f8949e42ba59851"},
            {"body": "SELECT * is not allowed, specify the required columns.","path": "workspace/Test.plsql","line": 14,"commit_id": "90de3a02bdf57cb64bdb7f934f8949e42ba59851"}
          ]'

          for item in $(echo "$json" | jq -c '.[]'); do
            echo "Processing item:"
            echo "$item"
            echo "--------"
          done
