name: PLSQL Code Review

on:
  pull_request:
    branches:
      - main # Update with your branch name

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'

      - name: Get .plsql files
        run: |
          find . -name "*.plsql" > plsql_files.txt

      - name: Run IfsCodeReview.jar
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          java -jar .github/IfsCodeReview.jar $COMMIT_ID workspace/Test.plsql
        working-directory: ${{ github.workspace }}

      - name: Print comments.json
        run: cat comments.json
        working-directory: ${{ github.workspace }}
        
      - name: Add Comments to PR
        run: |
          # Read the JSON file containing comments
          COMMENTS=$(cat comments.json)
          
          # Post comments to the Pull Request using GitHub API
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$COMMENTS" \
            https://api.github.com/repos/:owner/:repo/issues/:issue_number/comments
