name: Add Comments to PR

on:
  pull_request:
    branches:
      - main

jobs:
  code-review:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'

      - name: Run IfsCodeReview.jar
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          java -jar .github/IfsCodeReview.jar $COMMIT_ID workspace/Test.plsql
        working-directory: ${{ github.workspace }}

      - name: Print comments.json
        run: cat comments.json
        working-directory: ${{ github.workspace }}

      - name: Add Comments to PR
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const comments = JSON.parse(fs.readFileSync('comments.json', 'utf8'));

            for (const comment of comments) {
              await github.repos.createCommitComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: context.payload.pull_request.head.sha,
                body: comment.body,
                path: comment.path,
                position: comment.position
              });
            }
