name: Add Comments to PR

on:
  pull_request:
    branches:
      - main

jobs:
  code-review:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'

      - name: Run IfsCodeReview.jar
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          OWNER_ID=${{github.repository_owner}}
          REPO_ID=${{github.repository}}
          PR_NO=${{github.event.number}}
          java -jar .github/IfsCodeReview.jar $COMMIT_ID workspace/Test.plsql $OWNER_ID $REPO_ID $PR_NO
        working-directory: ${{ github.workspace }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Print comments.json
        run: cat comments.json
        working-directory: ${{ github.workspace }}
